# Generated by Django 3.0.5 on 2020-04-17 07:50

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csusers', '0001_initial'),
        ('videos', '0001_initial'),
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuserplaylist',
            name='videos',
            field=models.ManyToManyField(related_name='playlists', through='csusers.PlaylistVideo', to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='completes',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_by', to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='last_played',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='csusers.CSUserPlaylist'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='plays',
            field=models.ManyToManyField(blank=True, null=True, related_name='played_by', to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Site'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='skips',
            field=models.ManyToManyField(blank=True, null=True, related_name='skipped_by', to='videos.Video'),
        ),
        migrations.AddField(
            model_name='csuser',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
