// Generated by CoffeeScript 1.7.1
(function() {
  var $, DomManager, Player, ScriptLoader, Surface, VideoFile,
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  $(function() {
    var surface;
    window.media = [
      {
        ad: true,
        src: {
          mp4: "src/propel.mp4",
          webm: "src/propel.webm"
        },
        thumb: "",
        poster: "src/poster.png",
        title: "Advertisement",
        url: "https://www.facebook.com/propel"
      }, {
        ad: false,
        src: {
          mp4: "src/new.mp4",
          webm: "src/new.webm"
        },
        thumb: "thumb-new.png",
        poster: "",
        title: "See What's New in Shape Magazine",
        url: ""
      }, {
        ad: false,
        src: {
          mp4: "src/miller.mp4",
          webm: "src/miller.webm"
        },
        thumb: "thumb-miller.png",
        poster: "",
        title: "Marissa Miller's Shape Magazine Cover",
        url: ""
      }, {
        ad: false,
        src: {
          mp4: "src/audrina.mp4",
          webm: "src/audrina.webm"
        },
        thumb: "thumb-audrina.png",
        poster: "src/audrina.png",
        title: "Behind The Scenes With Audrina Patridge",
        url: ""
      }, {
        ad: false,
        src: {
          mp4: "src/brooke.mp4",
          webm: "src/brooke.webm"
        },
        thumb: "thumb-brooke.png",
        poster: "",
        title: "Brooke Burke's Shape Magazine Cover Shoot",
        url: ""
      }, {
        ad: false,
        src: {
          mp4: "src/olivia.mp4",
          webm: "src/olivia.webm"
        },
        thumb: "thumb-olivia.png",
        poster: "",
        title: "Olivia Munn's Shape Magazine Photoshoot",
        url: ""
      }
    ];
    return surface = new Surface("ShapeTV", 1500);
  });

  ScriptLoader = (function() {
    function ScriptLoader() {
      var callback, compressed, lib, loadCallback, options, s, version, _i;
      options = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), callback = arguments[_i++];
      this.libraries = {
        jQuery: "http://ajax.googleapis.com/ajax/libs/jquery/$version/jquery.js",
        videoJs: "vjs/video.dev.js"
      };
      lib = options[0], version = options[1], compressed = options[2];
      if (this.libraries[lib]) {
        lib = this.libraries[lib];
      }
      loadCallback = (function(_this) {
        return function() {
          if (_this.loaded) {
            return;
          }
          _this.loaded = true;
          return callback();
        };
      })(this);
      s = document.createElement('script');
      s.onload = loadCallback;
      s.onreadystatechange = function() {
        if (/loaded|complete/.test(s.readyState)) {
          return loadCallback();
        }
      };
      s.src = lib.replace('$version', version);
      if (compressed) {
        lib = lib.replace('.js', '.min.js');
      }
      document.getElementsByTagName('head')[0].appendChild(s);
    }

    return ScriptLoader;

  })();

  DomManager = (function() {
    function DomManager() {
      this.getStyle = __bind(this.getStyle, this);
      this.get = __bind(this.get, this);
      this.appendDivToParent = __bind(this.appendDivToParent, this);
      this.appendDivToBody = __bind(this.appendDivToBody, this);
      this.body = document.getElementsByTagName("body")[0];
      this.head = document.getElementsByTagName("head")[0];
    }

    DomManager.prototype.appendDivToBody = function(id) {
      var s;
      s = document.createElement("div");
      s.id = id;
      return this.body.appendChild(s);
    };

    DomManager.prototype.appendDivToParent = function(id, parent_id) {
      var parent, s;
      s = document.createElement("div");
      s.id = id;
      parent = document.getElementById(parent_id);
      return parent.appendChild(s);
    };

    DomManager.prototype.get = function(id) {
      var e;
      e = document.getElementById(id);
      return e;
    };

    DomManager.prototype.getStyle = function(url) {
      var l;
      l = document.createElement("link");
      l.href = url;
      l.rel = "stylesheet";
      l.type = "text/css";
      return this.head.appendChild(l);
    };

    return DomManager;

  })();

  Player = (function() {
    function Player(id, parent_id) {
      this.showProgressBar = __bind(this.showProgressBar, this);
      this.hideProgressBar = __bind(this.hideProgressBar, this);
      this.isPlaying = __bind(this.isPlaying, this);
      this.set_fullscreen_action = __bind(this.set_fullscreen_action, this);
      this.disable_fullscreen = __bind(this.disable_fullscreen, this);
      this.enable_fullscreen = __bind(this.enable_fullscreen, this);
      this.moveToParentWithId = __bind(this.moveToParentWithId, this);
      this.setCurrentTime = __bind(this.setCurrentTime, this);
      this.loadedmetadata = __bind(this.loadedmetadata, this);
      this.ready = __bind(this.ready, this);
      this.onpause = __bind(this.onpause, this);
      this.onplay = __bind(this.onplay, this);
      this.ended = __bind(this.ended, this);
      this.timeUpdate = __bind(this.timeUpdate, this);
      this.on = __bind(this.on, this);
      this.isMuted = __bind(this.isMuted, this);
      this.timeRemaining = __bind(this.timeRemaining, this);
      this.currentTime = __bind(this.currentTime, this);
      this.duration = __bind(this.duration, this);
      this.loadFile = __bind(this.loadFile, this);
      this.unmute = __bind(this.unmute, this);
      this.mute = __bind(this.mute, this);
      this.pause = __bind(this.pause, this);
      this.play = __bind(this.play, this);
      var p;
      this.id = id;
      this.parent_id = parent_id;
      p = document.createElement("video");
      p.setAttribute("id", id);
      p.setAttribute("class", "video-js vjs-default-skin vjs-big-play-button");
      p.setAttribute("height", "100%");
      p.setAttribute("width", "100%");
      p.setAttribute("data-setup", "{}");
      p.setAttribute("controls", "");
      document.getElementById(parent_id).appendChild(p);
      this.elem = videojs(id);
      this.playing = false;
      this.elem.on("play", (function(_this) {
        return function() {
          return _this.playing = true;
        };
      })(this));
      this.elem.on("pause", (function(_this) {
        return function() {
          return _this.playing = false;
        };
      })(this));
    }

    Player.prototype.play = function() {
      return this.elem.play();
    };

    Player.prototype.pause = function() {
      return this.elem.pause();
    };

    Player.prototype.mute = function() {
      return this.elem.volume(0);
    };

    Player.prototype.unmute = function() {
      return this.elem.volume(1);
    };

    Player.prototype.loadFile = function(vf) {
      var s;
      s = vf.sources();
      this.elem.src([
        {
          type: "video/mp4",
          src: s.mp4
        }, {
          type: "video/webm",
          src: s.webm
        }
      ]);
      if (vf.poster()) {
        return this.elem.poster(vf.poster());
      }
    };

    Player.prototype.duration = function() {
      return this.elem.duration();
    };

    Player.prototype.currentTime = function() {
      return this.elem.currentTime();
    };

    Player.prototype.timeRemaining = function() {
      return this.duration() - this.currentTime();
    };

    Player.prototype.isMuted = function() {
      return this.elem.muted();
    };

    Player.prototype.on = function(callback, func) {
      return this.elem.on(callback, func());
    };

    Player.prototype.timeUpdate = function(func) {
      return this.elem.on("timeupdate", func);
    };

    Player.prototype.ended = function(func) {
      return this.elem.on("ended", func);
    };

    Player.prototype.onplay = function(func) {
      return this.elem.on("play", func);
    };

    Player.prototype.onpause = function(func) {
      return this.elem.on("pause", func);
    };

    Player.prototype.ready = function(func) {
      return this.elem.ready(func);
    };

    Player.prototype.loadedmetadata = function(func) {
      return this.elem.on("loadedmetadata", func);
    };

    Player.prototype.setCurrentTime = function(time) {
      return this.elem.currentTime(time);
    };

    Player.prototype.moveToParentWithId = function(new_parent_id) {
      var container, new_parent, player_div;
      container = document.getElementById(this.parent_id);
      player_div = document.getElementById(this.id);
      container.removeChild(player_div);
      new_parent = document.getElementById(new_parent_id);
      new_parent.appendChild(player_div);
      player_div.width = new_parent.width;
      player_div.height = new_parent.height;
      return this.parent_id = new_parent_id;
    };

    Player.prototype.enable_fullscreen = function() {
      return $(".vjs-fullscreen-control").css("display", "inline");
    };

    Player.prototype.disable_fullscreen = function() {
      return $(".vjs-fullscreen-control").css("display", "none");
    };

    Player.prototype.set_fullscreen_action = function(func) {
      return $(".vjs-fullscreen-control")[0].onclick = func;
    };

    Player.prototype.isPlaying = function() {
      return this.elem.isPlaying();
    };

    Player.prototype.hideProgressBar = function() {
      return this.elem.controlBar.progressControl.hide();
    };

    Player.prototype.showProgressBar = function() {
      return this.elem.controlBar.progressControl.show();
    };

    return Player;

  })();

  Surface = (function() {
    function Surface(site_name, delay) {
      var item, run_surface, vf, _i, _len, _ref;
      this.site_name = site_name;
      this.remove_overlay = __bind(this.remove_overlay, this);
      this.set_blur = __bind(this.set_blur, this);
      this.update_current_time = __bind(this.update_current_time, this);
      this.toggle_mute = __bind(this.toggle_mute, this);
      this.toggle_slug = __bind(this.toggle_slug, this);
      this.rewind = __bind(this.rewind, this);
      this.forward = __bind(this.forward, this);
      this.load_UI = __bind(this.load_UI, this);
      this.next_content_title = __bind(this.next_content_title, this);
      this.hide_slug = __bind(this.hide_slug, this);
      this.enable_navigation = __bind(this.enable_navigation, this);
      this.disable_navigation = __bind(this.disable_navigation, this);
      this.enable_minimise = __bind(this.enable_minimise, this);
      this.disable_minimise = __bind(this.disable_minimise, this);
      this.maximise = __bind(this.maximise, this);
      this.minimise = __bind(this.minimise, this);
      this.play_previous_video = __bind(this.play_previous_video, this);
      this.play_next_video = __bind(this.play_next_video, this);
      this.current_video = __bind(this.current_video, this);
      this.current_video_index = parseInt(this.getCookie("gmcs-surface-current-video-index"));
      if (isNaN(this.current_video_index)) {
        this.current_video_index = 0;
      }
      this.current_time = parseInt(this.getCookie("gmcs-surface-current_time"));
      console.log(this.current_time);
      if (isNaN(this.current_time)) {
        this.current_time = 0;
      }
      this.start_minimised = parseInt(this.getCookie("gmcs-surface-minimised"));
      if (isNaN(this.start_minimised)) {
        this.start_minimised = 0;
      }
      this.start_slug_closed = parseInt(this.getCookie("gmcs-surface-start-slug-closed"));
      if (isNaN(this.start_slug_closed)) {
        this.start_slug_closed = 0;
      }
      console.log("start minimised = " + this.start_minimised);
      console.log("Current index = " + this.current_video_index);
      console.log("Current time = " + this.current_time);
      console.log("start slug closed = " + this.start_slug_closed);
      this.minimised = false;
      this.isSlugClosed = false;
      this.player = null;
      this.videos = [];
      _ref = window.media;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        vf = new VideoFile(item.src, 0, item.poster, item.title, item.url, item.ad, item.thumb);
        this.videos.push(vf);
      }
      this.dom = new DomManager();
      this.dom.getStyle("src/style.css");
      this.dom.getStyle("vjs/video-js.css");
      run_surface = (function(_this) {
        return function() {
          _this.set_blur();
          return new ScriptLoader("videoJs", _this.load_UI);
        };
      })(this);
      setTimeout(run_surface, delay);
    }

    Surface.prototype.current_video = function() {
      return this.videos[this.current_video_index];
    };

    Surface.prototype.play_next_video = function() {
      this.current_time = 0;
      if (this.current_video_index < this.videos.length - 1) {
        this.current_video_index = this.current_video_index + 1;
        console.log(this.current_video_index);
        this.player.loadFile(this.current_video());
        this.$video_title.html(this.current_video().title());
        this.player.play();
        this.setCookie("gmcs-surface-current-video-index", this.current_video_index, 10000);
        $("#cs-footer-text").text(this.next_content_title());
        if (this.current_video().isAd()) {
          this.disable_minimise();
          this.disable_navigation();
          console.log("isad");
          return this.player.hideProgressBar();
        } else {
          console.log("not ad");
          this.enable_minimise();
          this.enable_navigation();
          return this.player.showProgressBar();
        }
      }
    };

    Surface.prototype.play_previous_video = function() {
      var temp_index, _results;
      console.log("play previous reached");
      temp_index = this.current_video_index - 1;
      _results = [];
      while (temp_index >= 0) {
        console.log("temp index is " + temp_index);
        if (!this.videos[temp_index].isAd()) {
          console.log("Index is not ad");
          this.current_video_index = temp_index;
          console.log("Changed index to " + this.current_video_index);
          this.player.loadFile(this.current_video());
          this.$video_title.html(this.current_video().title());
          this.player.play();
          this.setCookie("gmcs-surface-current-video-index", this.current_video_index, 10000);
          this.enable_minimise();
          this.enable_navigation();
          this.player.showProgressBar();
          $("#cs-footer-text").text(this.next_content_title());
          break;
        } else {
          console.log("Index is ad");
        }
        _results.push(temp_index = temp_index - 1);
      }
      return _results;
    };

    Surface.prototype.minimise = function(start_closed) {
      var playing;
      if (start_closed == null) {
        start_closed = false;
      }
      this.$slugCloseButton.css("display", "inline");
      if (this.player.playing) {
        playing = true;
      } else {
        playing = false;
      }
      this.current_video().setPosition(this.player.currentTime());
      this.remove_overlay();
      this.$wrapper.hide();
      this.player.moveToParentWithId("cs-small-player-container");
      this.player.enable_fullscreen();
      $("#cs-slug-wrapper").show("100");
      this.minimised = true;
      if (playing) {
        this.player.play();
      }
      this.setCookie("gmcs-surface-minimised", 1, 10000);
      if (start_closed) {
        return this.toggle_slug();
      }
    };

    Surface.prototype.maximise = function() {
      this.$slugCloseButton.css("display", "none");
      if (this.minimised === true) {
        this.player.disable_fullscreen();
        this.hide_slug();
        this.set_blur();
        this.player.moveToParentWithId("cs-player-container");
        this.$wrapper.show();
        this.player.play();
        this.minimised = false;
        return this.setCookie("gmcs-surface-minimised", 0, 10000);
      }
    };

    Surface.prototype.disable_minimise = function() {
      if (this.current_video().isAd()) {
        $("#cs-close").addClass("cs-close-inactive");
        return $("#cs-close").attr('onclick', '').unbind('click');
      }
    };

    Surface.prototype.enable_minimise = function() {
      $("#cs-close").removeClass("cs-close-inactive");
      $("#cs-close").attr('onclick', '').unbind('click');
      return $("#cs-close").click((function(_this) {
        return function() {
          return _this.minimise();
        };
      })(this));
    };

    Surface.prototype.disable_navigation = function() {
      console.log("disabling nav");
      $("#cs-forward").addClass("cs-forward-disable");
      $("#cs-forward").attr('onclick', '').unbind('click');
      $("#cs-rewind").addClass("cs-rewind-disable");
      return $("#cs-rewind").attr('onclick', '').unbind('click');
    };

    Surface.prototype.enable_navigation = function() {
      var post_content, prior_content, temp_index;
      temp_index = this.current_video_index - 1;
      prior_content = false;
      while (temp_index >= 0) {
        if (!this.videos[temp_index].isAd()) {
          prior_content = true;
        }
        temp_index = temp_index - 1;
      }
      if (prior_content) {
        $("#cs-rewind").show();
      } else {
        $("#cs-rewind").hide();
      }
      temp_index = this.current_video_index + 1;
      post_content = false;
      while (temp_index < this.videos.length) {
        if (!this.videos[temp_index].isAd()) {
          post_content = true;
        }
        temp_index = temp_index + 1;
      }
      if (post_content) {
        $("#cs-forward").show();
      } else {
        $("#cs-forward").hide();
      }
      console.log("enabling nav");
      $("#cs-forward").removeClass("cs-forward-disable");
      $("#cs-forward").attr('onclick', '').unbind('click');
      $("#cs-forward").click(this.forward);
      $("#cs-rewind").removeClass("cs-rewind-disable");
      $("#cs-rewind").attr('onclick', '').unbind('click');
      return $("#cs-rewind").click(this.rewind);
    };

    Surface.prototype.hide_slug = function() {
      this.current_video().setPosition(this.player.currentTime());
      return $("#cs-slug-wrapper").hide();
    };

    Surface.prototype.next_content_title = function() {
      var temp_index;
      temp_index = this.current_video_index + 1;
      while (temp_index < this.videos.length) {
        if (!this.videos[temp_index].isAd()) {
          if (this.videos[this.current_video_index].isAd()) {
            $("#cs-footer").attr('onclick', '').unbind('click');
            $("#cs-footer").removeClass("footer-enabled");
            return "Coming Up: " + this.videos[temp_index].title();
          } else {
            $("#cs-footer").attr('onclick', '').unbind('click');
            $("#cs-footer").click(this.forward);
            $("#cs-footer").addClass("footer-enabled");
            return "Next: " + this.videos[temp_index].title();
          }
        }
        temp_index = temp_index + 1;
      }
      return "";
    };

    Surface.prototype.load_UI = function() {
      var html, label, player_container, s;
      s = document.createElement("div");
      s.id = "cs-wrapper";
      html = document.getElementsByTagName("html")[0];
      html.appendChild(s);
      this.dom.appendDivToParent("cs-overlay", "cs-wrapper");
      this.dom.appendDivToParent("cs-header", "cs-wrapper");
      this.dom.appendDivToParent("cs-close", "cs-header");
      this.dom.appendDivToParent("cs-main", "cs-wrapper");
      this.dom.appendDivToParent("cs-info-wrapper", "cs-main");
      this.dom.appendDivToParent("cs-top-line", "cs-info-wrapper");
      this.dom.appendDivToParent("cs-rule", "cs-info-wrapper");
      this.dom.appendDivToParent("cs-bottom-line", "cs-info-wrapper");
      this.dom.appendDivToParent("cs-label", "cs-top-line");
      this.dom.appendDivToParent("cs-video-title", "cs-bottom-line");
      this.dom.appendDivToParent("cs-video-time-remaining", "cs-bottom-line");
      this.dom.appendDivToParent("cs-player-wrapper", "cs-main");
      this.dom.appendDivToParent("cs-rewind", "cs-player-wrapper");
      this.dom.appendDivToParent("cs-forward", "cs-player-wrapper");
      this.dom.appendDivToParent("cs-player-container", "cs-player-wrapper");
      this.dom.appendDivToParent("cs-footer", "cs-player-wrapper");
      this.dom.appendDivToParent("cs-footer-text", "cs-footer");
      this.$wrapper = $("#cs-wrapper");
      this.$video_title = $("#cs-video-title");
      label = $("#cs-label");
      player_container = $("#cs-player-container");
      $("#cs-close").addClass("cs-minimise");
      $("#cs-rewind").hide();
      player_container.addClass("largeVideoWrapper");
      label.html(this.site_name);
      if (this.current_video().isAd()) {
        this.$video_title.html(this.videos[this.current_video_index + 1].title());
      } else {
        this.$video_title.html(this.current_video().title());
      }
      this.enable_minimise();
      this.player = new Player("cs-video-player", "cs-player-container");
      this.player.ready((function(_this) {
        return function() {
          _this.player.loadFile(_this.current_video());
          _this.player.mute();
          if (_this.current_time > 0) {
            _this.player.loadedmetadata(function() {
              return _this.player.setCurrentTime(_this.current_time);
            });
          }
          _this.player.ended(_this.play_next_video);
          _this.player.set_fullscreen_action(_this.maximise);
          $("#cs-footer-text").text(_this.next_content_title());
          if (_this.current_video().isAd()) {
            _this.disable_navigation();
            _this.player.onplay(function() {
              return _this.disable_minimise();
            });
            _this.player.hideProgressBar();
          } else {
            _this.enable_navigation();
          }
          _this.player.onplay(function() {
            return _this.$video_title.html(_this.current_video().title());
          });
          _this.player.timeUpdate(_this.update_current_time);
          _this.slugCloseButton = _this.player.elem.addChild('button', {});
          if (_this.isSlugClosed) {
            _this.slugCloseButton.addClass("slug-open-btn slug-slide-button");
          } else {
            _this.slugCloseButton.addClass("slug-close-btn slug-slide-button");
          }
          _this.slugCloseButton.on("click", _this.toggle_slug);
          _this.$slugCloseButton = $(".slug-slide-button");
          return _this.$slugCloseButton.css("display", "none");
        };
      })(this));
      this.dom.appendDivToBody("cs-slug-wrapper");
      this.$slugWrapper = $("#cs-slug-wrapper");
      if (this.isSlugClosed) {
        this.$slugWrapper.addClass("slug-closed");
      } else {
        this.$slugWrapper.addClass("slug-open");
      }
      this.dom.appendDivToParent("cs-small-player-container", "cs-slug-wrapper");
      player_container = $("#cs-small-player-container");
      player_container.addClass("smallVideoWrapper");
      this.hide_slug();
      if (this.start_minimised > 0) {
        if (this.start_slug_closed > 0) {
          return this.minimise(true);
        } else {
          return this.minimise(false);
        }
      }
    };

    Surface.prototype.forward = function() {
      console.log("forward");
      if (!this.current_video().isAd()) {
        return this.play_next_video();
      }
    };

    Surface.prototype.rewind = function() {
      return this.play_previous_video();
    };

    Surface.prototype.toggle_slug = function() {
      if (!this.isSlugClosed) {
        console.log("it's not closed - closing");
        this.$slugWrapper.removeClass("slug-open");
        this.$slugWrapper.addClass("slug-closed");
        this.$slugCloseButton.removeClass("slug-close-btn");
        this.$slugCloseButton.addClass("slug-open-btn");
        this.player.pause();
        this.isSlugClosed = true;
        return this.setCookie("gmcs-surface-start-slug-closed", 1, 10000);
      } else {
        console.log("it's closed - opening");
        this.$slugWrapper.removeClass("slug-closed");
        this.$slugWrapper.addClass("slug-open");
        this.$slugCloseButton.removeClass("slug-open-btn");
        this.$slugCloseButton.addClass("slug-close-btn");
        this.player.play();
        this.isSlugClosed = false;
        return this.setCookie("gmcs-surface-start-slug-closed", 0, 10000);
      }
    };

    Surface.prototype.toggle_mute = function() {
      if (this.player.isMuted()) {
        return this.player.unmute();
      } else {
        return this.player.mute();
      }
    };

    Surface.prototype.update_current_time = function() {
      if (this.player.playing) {
        return this.setCookie("gmcs-surface-current_time", this.player.currentTime(), 10000);
      }
    };

    Surface.prototype.set_blur = function() {
      $("body").css("filter", "blur(15px)");
      $("body").css("filter", "url(src/blur.svg#blur)");
      $("body").css("-webkit-filter", "blur(15px)");
      $("body").css("-moz-filter", "blur(15px)");
      $("body").css("-o-filter", "blur(15px)");
      $("body").css("-ms-filter", "blur(15px)");
      return $('html, body').css({
        'overflow': 'hidden',
        'height': '100%'
      });
    };

    Surface.prototype.remove_overlay = function() {
      $("body").css("-webkit-filter", "blur(0px)");
      $("html").css("filter", "blur(0px)");
      $("body").css("filter", "url(src/blur.svg#noBlur)");
      $("body").css("-moz-filter", "blur(0px)");
      $("body").css("-o-filter", "blur(0px)");
      $("body").css("-ms-filter", "blur(0px)");
      return $('html, body').css({
        'overflow': 'auto',
        'height': 'auto'
      });
    };

    Surface.prototype.setCookie = function(name, value, days) {
      var date, expires;
      if (days) {
        date = new Date();
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        expires = "; expires=" + date.toGMTString();
      } else {
        expires = "";
      }
      return document.cookie = name + "=" + value + expires + "; path=/";
    };

    Surface.prototype.getCookie = function(name) {
      var c, ca, i, nameEQ;
      nameEQ = name + "=";
      ca = document.cookie.split(";");
      i = 0;
      while (i < ca.length) {
        c = ca[i];
        while (c.charAt(0) === " ") {
          c = c.substring(1, c.length);
        }
        if (c.indexOf(nameEQ) === 0) {
          return c.substring(nameEQ.length, c.length);
        }
        i++;
      }
      return null;
    };

    Surface.prototype.deleteCookie = function(name) {
      return setCookie(name, "", -1);
    };

    return Surface;

  })();

  VideoFile = (function() {
    function VideoFile(src, position, poster, title, video_url, ad, thumb) {
      this.video_url = video_url;
      this.ad = ad;
      this.thumb = thumb;
      this.thumbnail = __bind(this.thumbnail, this);
      this.isAd = __bind(this.isAd, this);
      this.poster = __bind(this.poster, this);
      this.url = __bind(this.url, this);
      this.title = __bind(this.title, this);
      this.setPosition = __bind(this.setPosition, this);
      this.position = __bind(this.position, this);
      this.sources = __bind(this.sources, this);
      this.file_src = src != null ? src : "";
      this.playback_position = position != null ? position : 0;
      this.video_poster = poster != null ? poster : "";
      this.video_title = title != null ? title : "";
    }

    VideoFile.prototype.sources = function() {
      return this.file_src;
    };

    VideoFile.prototype.position = function() {
      return this.playback_position;
    };

    VideoFile.prototype.setPosition = function(pos) {
      return this.playback_position = pos;
    };

    VideoFile.prototype.title = function() {
      return this.video_title;
    };

    VideoFile.prototype.url = function() {
      return this.video_url;
    };

    VideoFile.prototype.poster = function() {
      if (this.video_poster.length > 0) {
        return this.video_poster;
      }
      return null;
    };

    VideoFile.prototype.isAd = function() {
      return this.ad;
    };

    VideoFile.prototype.thumbnail = function() {
      return this.thumb;
    };

    return VideoFile;

  })();

}).call(this);
