// Generated by CoffeeScript 1.6.3
(function() {
  var $, DomManager, Surface,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  $(function() {
    var surface;
    return surface = new Surface("Radar Online");
  });

  DomManager = (function() {
    function DomManager() {
      this.getStyle = __bind(this.getStyle, this);
      this.getScript = __bind(this.getScript, this);
      this.get = __bind(this.get, this);
      this.appendDivToParent = __bind(this.appendDivToParent, this);
      this.appendDivOutsideBody = __bind(this.appendDivOutsideBody, this);
      this.body = document.getElementsByTagName("body")[0];
      this.head = document.getElementsByTagName("head")[0];
      this.html = document.getElementsByTagName("html")[0];
    }

    DomManager.prototype.appendDivOutsideBody = function(id) {
      var s;
      s = document.createElement("div");
      s.id = id;
      return this.html.appendChild(s);
    };

    DomManager.prototype.appendDivToParent = function(id, parent_id) {
      var parent, s;
      s = document.createElement("div");
      s.id = id;
      parent = document.getElementById(parent_id);
      return parent.appendChild(s);
    };

    DomManager.prototype.get = function(id) {
      var elem;
      elem = document.getElementById(id);
      return elem;
    };

    DomManager.prototype.getScript = function(url, success) {
      var done, script;
      done = false;
      script = document.createElement("script");
      script.src = url;
      script.onload = function() {
        if (!done && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) {
          done = true;
          if (typeof success === 'function') {
            return success();
          }
        }
      };
      script.onreadystatechange = script.onload;
      return this.head.appendChild(script);
    };

    DomManager.prototype.getStyle = function(url) {
      var l;
      l = document.createElement("link");
      l.href = url;
      l.rel = "stylesheet";
      l.type = "text/css";
      return this.head.appendChild(l);
    };

    return DomManager;

  })();

  Surface = (function() {
    function Surface(site_name) {
      this.site_name = site_name;
      this.remove_overlay = __bind(this.remove_overlay, this);
      this.update_time_remaining = __bind(this.update_time_remaining, this);
      this.set_bindings = __bind(this.set_bindings, this);
      this.load_elements = __bind(this.load_elements, this);
      this.set_overlay = __bind(this.set_overlay, this);
      this.dom = new DomManager();
      this.dom.getStyle("src/style.css");
      this.set_overlay();
      this.load_elements();
    }

    Surface.prototype.set_overlay = function() {
      $("body").css("-webkit-filter", "blur(20px)");
      $("body").css("filter", "blur(20px)");
      $('html, body').css({
        'overflow': 'hidden',
        'height': '100%'
      });
      this.dom.appendDivOutsideBody("cs-wrapper");
      this.dom.appendDivToParent("cs-overlay", "cs-wrapper");
      return this.$wrapper = $("#cs-wrapper");
    };

    Surface.prototype.load_elements = function() {
      var label, v;
      this.dom.appendDivToParent("cs-header", "cs-wrapper");
      this.dom.appendDivToParent("cs-close", "cs-header");
      this.dom.appendDivToParent("cs-main", "cs-wrapper");
      this.dom.appendDivToParent("cs-info-wrapper", "cs-wrapper");
      this.dom.appendDivToParent("cs-top-line", "cs-info-wrapper");
      this.dom.appendDivToParent("cs-rule", "cs-info-wrapper");
      this.dom.appendDivToParent("cs-bottom-line", "cs-info-wrapper");
      this.dom.appendDivToParent("cs-label", "cs-top-line");
      this.dom.appendDivToParent("cs-video-title", "cs-bottom-line");
      this.dom.appendDivToParent("cs-video-time-remaining", "cs-bottom-line");
      this.dom.appendDivToParent("cs-player-wrapper", "cs-wrapper");
      this.dom.appendDivToParent("cs-player-container", "cs-player-wrapper");
      this.dom.appendDivToParent("cs-footer", "cs-wrapper");
      this.dom.appendDivToParent("cs-video-title", "cs-wrapper");
      label = $("#cs-label");
      label.html(this.site_name + " TV");
      this.$video_title = $("#cs-video-title");
      this.$video_title.html("Meet the team behind Genesis Media");
      this.$video_time_remaining = $("#cs-video-time-remaining");
      this.$video_time_remaining.html("00:00");
      v = document.createElement("video");
      v.setAttribute("id", "cs-video-player");
      v.setAttribute("poster", "src/poster.png");
      v.src = "src/3.mp4";
      this.video = this.dom.get("cs-player-container").appendChild(v);
      this.video.play();
      return this.set_bindings();
    };

    Surface.prototype.set_bindings = function() {
      var _this = this;
      $("#cs-close").click(function() {
        return _this.remove_overlay();
      });
      return this.video.addEventListener('timeupdate', this.update_time_remaining);
    };

    Surface.prototype.update_time_remaining = function() {
      var mins, mins_text, secs, secs_text, time_in_secs;
      time_in_secs = this.video.duration - this.video.currentTime;
      mins = Math.floor(time_in_secs / 60);
      secs = Math.ceil(time_in_secs % 60);
      if (mins > 9) {
        mins_text = '' + mins;
      } else {
        mins_text = '0' + mins;
      }
      if (secs > 9) {
        secs_text = '' + secs;
      } else {
        secs_text = '0' + secs;
      }
      return this.$video_time_remaining.html(mins_text + ":" + secs_text);
    };

    Surface.prototype.remove_overlay = function() {
      $("body").css("-webkit-filter", "blur(0px)");
      $("html").css("filter", "blur(0px)");
      $('html, body').css({
        'overflow': 'auto',
        'height': 'auto'
      });
      return this.$wrapper.remove();
    };

    return Surface;

  })();

}).call(this);
